[package]
edition = "2021"
name = "stream-napi"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = ["napi4","async"] }
napi-derive = "2.12.2"
nvenc = { path = "../nvenc-rs/nvenc" }
webrtc-helper = { path = "../webrtc-helper" }
webrtc = "0.6.0"
log = "0.4.0"
rand = "0.8.5"
serde = "1.0.151"
futures-util = "0.3.25"
async-trait = "0.1.57"
serde_json = "1.0.91"
tokio = { version = "1.25.0", features = ["full"] }
warp = { version = "0.3.3", features = ["tls"] }

[build-dependencies]
napi-build = "2.0.1"

[dependencies.windows]
version = "0.43"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_System_Performance",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_Pointer",
    "Win32_UI_WindowsAndMessaging"
]
