/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export declare class IceServer {
  urls: Array<string>
  username: string
  credential: string
}
export declare class Configuration {
  iceServers: Array<IceServer>
}
export type WebRtc = WebRTC
export declare class WebRTC {
  static create(conf: Configuration): WebRtc
  sendMessage(message: string): Promise<void>
  onMessage(callback: (err:null|Error, result: string) => void): void
  onData(callback: (err:null|Error, result: string) => void): void
  onClose(callback: (err:null|Error) => void): void
  static startCapture(): Promise<ExternalObject<ScreenDuplicator>>
  init(captureLoop: ExternalObject<ScreenDuplicator>): void
}
