[package]
edition = "2021"
name = "webrtc_rust_client"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = ["async", "compat-mode", "napi4", "tokio_rt"] }
napi-derive = "2.12.2"
notify = "7.0.0"
serde = "1.0.216"
serde_json = "1.0.133"
tokio = "1.42.0"
webrtc = "0.12.0"
windows = { version = "0.58.0", features = ["Storage_Streams"] }
windows-capture = "1.4.2"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"

[profile.dev]
opt-level = 1