/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class IceServer {
  urls: Array<string>
  username: string
  credential: string
}
export declare class Configuration {
  iceServers: Array<IceServer>
  constructor(iceServers: Array<IceServer>)
}
export type WebRtcClass = WebRTC
export declare class WebRTC {
  static create(conf: Configuration): Promise<WebRtcClass>
  sendMessage(message: string): void
  onMessage(callback: (...args: any[]) => any): void
}
